name: Generate Snake

# 触发条件
on:
  schedule:
    # 每 12 小时自动运行一次生成最新的贪吃蛇
    - cron: "0 */12 * * *" 
  
  # 允许手动在 Actions 页面触发
  workflow_dispatch:
  
  # 当 main 分支有 push 时触发
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          # 你的 github 用户名
          github_user_name: thanatosmoe
          # 生成的文件名及路径（包含适配亮/暗主题的文件）
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            
      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          # 推送到 output 分支，README 里的图片正是从此分支读取
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
